version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Cela signifie que si le broker tombe en panne, aucun autre broker ne pourra enregistrer l'arrêt du consumer (ceci n'est pas notre cas, nous devons juste assurer la partie de test et de développement d'Apache Kafka).
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1  # Cela signifie que l’écri
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 # Les logs d'état des transactions dans Apache Kafka se réfèrent aux journaux utilisés pour enregistrer les informations sur l'état des transactions(si la transaction est echouée les messages ne seront pas visible pour le consumer et sinon il seront visible pour lui).
